//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lí_bán_hàng_lưu_niệm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCodeMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCodeMaterial()
        {
            this.tblGoods = new HashSet<tblGood>();
        }
    
        public int CodeMaterialID { get; set; }
        public string CodeMaterialName { get; set; }
        public string sources { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGood> tblGoods { get; set; }
    }
}
