//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lí_bán_hàng_lưu_niệm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGood()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int GoodID { get; set; }
        public string GoodName { get; set; }
        public int CodeMaterialID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string priceImport { get; set; }
        public string priceSell { get; set; }
        public byte[] Photos { get; set; }
        public string Description { get; set; }
    
        public virtual tblCodeMaterial tblCodeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
