//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lí_bán_hàng_lưu_niệm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdersDetail
    {
        public int OrderID { get; set; }
        public int customerID { get; set; }
        public string Amount { get; set; }
        public string Price { get; set; }
        public string Discount { get; set; }
        public string money { get; set; }
        public string Description { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
