//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lí_bán_hàng_lưu_niệm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrdersDetails = new HashSet<tblOrdersDetail>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string date { get; set; }
        public int GoodID { get; set; }
        public string money { get; set; }
        public string Description { get; set; }
    
        public virtual tblGood tblGood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdersDetail> tblOrdersDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
